[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      frame-ancestors 'self';
      frame-src 'self' https://*.firebaseapp.com https://*.firebase.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://*.firebaseio.com https://*.firebase.com https://*.googleapis.com;
    """
